-- CREATION DE LA BASE DE DONNÉES

DROP TABLE IF EXISTS ESTDUTHEME;
DROP TABLE IF EXISTS THEME;
DROP TABLE IF EXISTS ESTDUGENRE;
DROP TABLE IF EXISTS GENRE;
DROP TABLE IF EXISTS ESTEDITER;
DROP TABLE IF EXISTS EDITEUR;
DROP TABLE IF EXISTS JEU;


CREATE TABLE JEU (
  ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  NOM VARCHAR(100) DEFAULT NULL,
  DATESORTIE DATE DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE EDITEUR (
  ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  NOM VARCHAR(100) DEFAULT NULL,
  SIEGESOCIETE VARCHAR(100) DEFAULT NULL,
  DATECREATION DATE DEFAULT NULL,
  ETAT VARCHAR(100) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE ESTEDITER (
  IDJEU INT,
  idEditeur INT,
  CONSTRAINT pk_estediter PRIMARY KEY (IDJEU, idEditeur),
  CONSTRAINT fk_estediter_jeu FOREIGN KEY (IDJEU) REFERENCES JEU(ID) ON DELETE CASCADE,
  CONSTRAINT fk_estediter_editeur FOREIGN KEY (idEditeur) REFERENCES EDITEUR(ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE GENRE (
  ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  NOMGENRE VARCHAR(100) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE ESTDUGENRE (
  IDJEU INT,
  IDGENRE INT,
  CONSTRAINT pk_estdugenre PRIMARY KEY (IDJEU, IDGENRE),
  CONSTRAINT fk_estdugenre_jeu FOREIGN KEY (IDJEU) REFERENCES JEU(ID) ON DELETE CASCADE,
  CONSTRAINT fk_estdugenre_genre FOREIGN KEY (IDGENRE) REFERENCES GENRE(ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE THEME (
  ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  NOMTHEME VARCHAR(100) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE ESTDUTHEME (
  IDJEU INT,
  IDTHEME INT,
  CONSTRAINT pk_estdutheme PRIMARY KEY (IDJEU, IDTHEME),
  CONSTRAINT fk_estdutheme_jeu FOREIGN KEY (IDJEU) REFERENCES JEU(ID) ON DELETE CASCADE,
  CONSTRAINT fk_estdutheme_theme FOREIGN KEY (IDTHEME) REFERENCES THEME(ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO JEU     (NOM, DATESORTIE)                         VALUES ('The Legend of Zelda : Ocarina of Time', '1998-11-21');
INSERT INTO EDITEUR (NOM, SIEGESOCIETE, DATECREATION, ETAT)   VALUES ('NINTendo', 'Japon', '1883-09-23', 'OUVERT');
INSERT INTO GENRE   (NOMGENRE)                                VALUES ('RPG');
INSERT INTO THEME   (NOMTHEME)                                VALUES ('Fantasy');
